package ar.com.hotel.view;

import ar.com.hotel.App;
import ar.com.hotel.utils.MusicPlayer;
import java.io.IOException;

public class WelcomeView extends javax.swing.JFrame {

    private final MusicPlayer bgMusic = new MusicPlayer();
    private int xMouse, yMouse;
    private boolean isMusicActive = true;

    public WelcomeView() {
        initComponents();
        playBackgroundMusic();
    }

    private void playBackgroundMusic() {
        bgMusic.setFile(getClass().getResource("/ar/com/hotel/sounds/C418-Sweden.wav").getPath());
        bgMusic.play();
    }

    private void stopBackgroundMusic() {
        try {
            bgMusic.stop();
        } catch (IOException e) {
        }
    }

    private void toggleMusic() {
        if (isMusicActive) {
            toggleMusicBtn.setText("RESUMIR ♪");
            bgMusic.pause();
            isMusicActive = false;
        } else {
            toggleMusicBtn.setText("PAUSAR ♪");
            bgMusic.resume();
            isMusicActive = true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        toggleMusicBtn = new javax.swing.JButton();
        mainTitleLabel = new javax.swing.JLabel();
        enterBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();
        backgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(53, 35, 21));
        background.setMinimumSize(new java.awt.Dimension(1, 1));
        background.setOpaque(false);
        background.setPreferredSize(new java.awt.Dimension(854, 480));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        topBar.setOpaque(false);
        topBar.setPreferredSize(new java.awt.Dimension(0, 30));
        topBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topBarMouseDragged(evt);
            }
        });
        topBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topBarMousePressed(evt);
            }
        });

        searchLabel.setBackground(new java.awt.Color(80, 80, 80));
        searchLabel.setFont(new java.awt.Font("Minecraftia", 0, 14)); // NOI18N
        searchLabel.setForeground(new java.awt.Color(90, 90, 90));
        searchLabel.setText("  Hotelcraft Beta 1.4");

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addComponent(searchLabel)
                .addGap(0, 678, Short.MAX_VALUE))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        background.add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 854, -1));

        toggleMusicBtn.setBackground(new java.awt.Color(107, 107, 107));
        toggleMusicBtn.setFont(new java.awt.Font("Minecraftia", 0, 16)); // NOI18N
        toggleMusicBtn.setForeground(new java.awt.Color(224, 224, 224));
        toggleMusicBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/stone-bar-small.png"))); // NOI18N
        toggleMusicBtn.setText("PAUSAR ♪");
        toggleMusicBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        toggleMusicBtn.setBorderPainted(false);
        toggleMusicBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleMusicBtn.setFocusable(false);
        toggleMusicBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleMusicBtn.setPreferredSize(new java.awt.Dimension(196, 40));
        toggleMusicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMusicBtnActionPerformed(evt);
            }
        });
        background.add(toggleMusicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 384, -1, -1));

        mainTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/HotelCraft.png"))); // NOI18N
        background.add(mainTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        enterBtn.setBackground(new java.awt.Color(107, 107, 107));
        enterBtn.setFont(new java.awt.Font("Minecraftia", 0, 16)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(224, 224, 224));
        enterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/stone-bar-large.png"))); // NOI18N
        enterBtn.setText("INICIAR SESIÓN");
        enterBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        enterBtn.setBorderPainted(false);
        enterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterBtn.setFocusable(false);
        enterBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enterBtn.setPreferredSize(new java.awt.Dimension(400, 40));
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        background.add(enterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 216, -1, -1));

        exitBtn.setBackground(new java.awt.Color(107, 107, 107));
        exitBtn.setFont(new java.awt.Font("Minecraftia", 0, 16)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(224, 224, 224));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/stone-bar-small.png"))); // NOI18N
        exitBtn.setText("SALIR");
        exitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        exitBtn.setBorderPainted(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setFocusable(false);
        exitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitBtn.setPreferredSize(new java.awt.Dimension(196, 40));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        background.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 384, -1, -1));

        registerBtn.setBackground(new java.awt.Color(107, 107, 107));
        registerBtn.setFont(new java.awt.Font("Minecraftia", 0, 16)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(224, 224, 224));
        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/stone-bar-large.png"))); // NOI18N
        registerBtn.setText("REGISTRARSE");
        registerBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        registerBtn.setBorderPainted(false);
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.setFocusable(false);
        registerBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerBtn.setPreferredSize(new java.awt.Dimension(400, 40));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        background.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 270, -1, -1));

        mainTitle.setFont(new java.awt.Font("Minecraftia", 0, 16)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mainTitle.setText("Hecho con <3 por Gastón Giacobini ");
        background.add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 453, 854, 30));

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ar/com/hotel/img/main-title-background.gif"))); // NOI18N
        backgroundImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backgroundImg.setPreferredSize(new java.awt.Dimension(854, 480));
        background.add(backgroundImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topBarMouseDragged

    private void topBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topBarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topBarMousePressed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        this.stopBackgroundMusic();
        this.dispose();
        App.openLogin();
    }//GEN-LAST:event_enterBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        this.stopBackgroundMusic();
        this.dispose();
        App.openRegister();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void toggleMusicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMusicBtnActionPerformed
        this.toggleMusic();
    }//GEN-LAST:event_toggleMusicBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JButton enterBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JButton toggleMusicBtn;
    private javax.swing.JPanel topBar;
    // End of variables declaration//GEN-END:variables
}
